# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  dir: .
  main: .
  goos:
    - darwin
    - freebsd
    - linux
    - openbsd
    - windows
  ldflags:
  - -s -w -X github.com/oldthreefeng/stress/cmd.Version={{.Tag}} -X github.com/oldthreefeng/stress/cmd.Build={{.ShortCommit}} -X github.com/oldthreefeng/stress/cmd.BuildTime={{.Date}} -X github.com/oldthreefeng/stress/cmd.BuildBy=goreleaser
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dockers:
  -
    goos: linux

    goarch: amd64

    binaries:
      - stress

    image_templates:
      - "louisehong/{{.ProjectName}}:latest"
      - "louisehong/{{.ProjectName}}:{{.Tag}}"

    dockerfile: Dockerfile