# .travis.yml
language: go


# needed only if you use the docker pipe
services:
  - docker

script:
  - go test ./... # replace this with your test script
  - curl -sfL https://git.io/goreleaser | sh -s -- check # check goreleaser config for deprecations

after_success:
  # docker login is required if you want to push docker images.
  # DOCKER_PASSWORD should be a secret in your .travis.yml configuration.
  - test -n "$TRAVIS_TAG" && docker login -u=myuser -p="$DOCKER_PASSWORD"
  # snapcraft login is required if you want to push snapcraft packages to the
  # store.
  # You'll need to run `snapcraft export-login snap.login` and
  # `travis encrypt-file snap.login --add` to add the key to the travis
  # environment.

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux